src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UtilisateurRepository::class)]
class Utilisateur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom_utilisateur;

    #[ORM\Column(type: 'string', length: 255)]
    private $prenom_utilisateur;

    #[ORM\Column(type: 'string', length: 255)]
    private $email_utilisateur;

    #[ORM\Column(type: 'string')]
    private $phone_utilisateur;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $adresse_utilisateur;

    #[ORM\Column(type: 'date')]
    private $date_naissance;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $photo;

    #[ORM\OneToMany(mappedBy: 'utilisateur', targetEntity: Affection::class, orphanRemoval: true)]
    private $affections;

    public function __construct()
    {
        $this->affections = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomUtilisateur(): ?string
    {
        return $this->nom_utilisateur;
    }

    public function setNomUtilisateur(string $nom_utilisateur): self
    {
        $this->nom_utilisateur = $nom_utilisateur;

        return $this;
    }

    public function getPrenomUtilisateur(): ?string
    {
        return $this->prenom_utilisateur;
    }

    public function setPrenomUtilisateur(string $prenom_utilisateur): self
    {
        $this->prenom_utilisateur = $prenom_utilisateur;

        return $this;
    }

    public function getEmailUtilisateur(): ?string
    {
        return $this->email_utilisateur;
    }

    public function setEmailUtilisateur(string $email_utilisateur): self
    {
        $this->email_utilisateur = $email_utilisateur;

        return $this;
    }

    public function getPhoneUtilisateur(): ?string
    {
        return $this->phone_utilisateur;
    }

    public function setPhoneUtilisateur(string $phone_utilisateur): self
    {
        $this->phone_utilisateur = $phone_utilisateur;

        return $this;
    }

    public function getAdresseUtilisateur(): ?string
    {
        return $this->adresse_utilisateur;
    }

    public function setAdresseUtilisateur(?string $adresse_utilisateur): self
    {
        $this->adresse_utilisateur = $adresse_utilisateur;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection<int, Affection>
     */
    public function getAffections(): Collection
    {
        return $this->affections;
    }

    public function addAffection(Affection $affection): self
    {
        if (!$this->affections->contains($affection)) {
            $this->affections[] = $affection;
            $affection->setUtilisateur($this);
        }

        return $this;
    }

    public function removeAffection(Affection $affection): self
    {
        if ($this->affections->removeElement($affection)) {
            // set the owning side to null (unless already changed)
            if ($affection->getUtilisateur() === $this) {
                $affection->setUtilisateur(null);
            }
        }

        return $this;
    }
}

src/Form/UtilisateurType.php
<?php

namespace App\Form;

use App\Entity\Utilisateur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UtilisateurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_utilisateur', TextType::class, [
                'required' => true,
                'attr' => [
                    'class' => "form-control",
                    'placeholder' => "Enter le nom de l'utilisateur",
                ]
            ])

            ->add('prenom_utilisateur', TextType::class, [
                'required' => true,
                'attr' => [
                    'class' => "form-control",
                    'placeholder' => "Enter le prenom de l'utilisateur",
                ]
            ])

            ->add('email_utilisateur', EmailType::class, [
                'required' => true,
                "attr" => [
                    "class" => "form-control",
                    'placeholder' => "Enter l'email de l'utilisateur",
                ]
            ])
            
            ->add('phone_utilisateur', TelType::class, [
                'required' => true,
               "attr" => [
                    "class" => "form-control",
                    'placeholder' => "XXXXXXXX"
                ]
            ])

            ->add('adresse_utilisateur', TextType::class, [
                'required' => true,
                 "attr" => [
                    "class" => "form-control",
                    'placeholder' =>"Entrez l'adresse de l'utilisateur",
                ]
            ])

            ->add('date_naissance', DateType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'format' => 'dd/MM/yyyy',
                'required' => true,
                "attr" => [
                    "class" => "form-control datetimepicker-input",
                    'data-target'=>"#dateNaissance",
                    'placeholder'=>"dd/mm/yyyy"
               
                ]
            ])

            ->add('photo', FileType::class, [
                'data_class' => null,
                'required' => false,
                "attr" => [
                    "class" => "custom-file-input",
                ]
                
            ])

            ->add('submit', SubmitType::class, [
                'label' => "Enregistrer",
                "attr" => [
                    'class' => "btn btn-primary",
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Utilisateur::class,
        ]);
    }
}

src/Controller/UtilisateurController.php
<?php

namespace App\Controller;

use App\Entity\Utilisateur;
use App\Form\UtilisateurType;
use App\Repository\UtilisateurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UtilisateurController extends AbstractController
{
   /**
    * @Route("/utilisateur",  name="utilisateur")
    */
    public function index(UtilisateurRepository $userRepo): Response
    {

        $this->addFlash('success',  'Utilisateur modifié avec succès !! ');
        $allUsers = $userRepo->findAll();

        return $this->render('utilisateur/utilisateur.html.twig', compact("allUsers"));
    }


    /**
    *  @Route("/add/utilisateur",  name="add_utilisateur")
    *  @Route("/edit/{id}/utilisateur", name="edit_utilisateur")
    */
    public function addUtilisateur(Utilisateur $user = null,   Request  $request, EntityManagerInterface $entityManager): Response 
    {

        // On veut faire une mise a jour !! 
        if ($user) {

            $userForm = $this->createForm(UtilisateurType::class, $user);
            $userForm->handleRequest($request);
            if ($userForm->isSubmitted() && $userForm->isValid()) {
            $entityManager->persist($user);
            $entityManager->flush();
            $this->addFlash('success',  'Utilisateur modifié avec succès !! ');
            return $this->redirectToRoute('utilisateur');
            }


        }  else {
            // On veut faire une insertion
            $user = new Utilisateur();
            $userForm = $this->createForm(UtilisateurType::class, $user);
            $userForm->handleRequest($request);

            if ($userForm->isSubmitted() && $userForm->isValid()) {
            $entityManager->persist($user);
            $entityManager->flush();
            $this->addFlash('success',  'Utilisateur creer avec succès !! ');
            return $this->redirectToRoute('utilisateur');
            }

        }


        return $this->render('utilisateur/add_utilisateur.html.twig', [
            "userForm" => $userForm->createView(),
        ]);
    }


    /**
    * @Route("/see/{id}/profile",  name="profile_utilisateur")
    */
    public function showUtilisateur(Utilisateur $user): Response 
    {
        

        return $this->render('utilisateur/see_utilisateur.html.twig', compact('user'));
    }
}

templates/utilisateur/add_utilisateur.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Matrix - Add - Utilisateurs
{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{asset('assets/css/dataTables.bootstrap4.min.css') }}">
	<link rel="stylesheet" href="{{asset('assets/css/utilisateur.css') }}">
	<link rel="stylesheet" href="{{ asset('assets/css/tempusdominus.min.css') }} ">
{% endblock %}


{% block cental_content %}

	<!-- Content Wrapper. Contains page content -->
	<div
		class="content-wrapper">
		<!-- Content Header (Page header) -->
		<div class="content-header">
			<div class="container-fluid">
				<div class="row mb-2">
					<div class="col-sm-6">
						<h1 class="m-0">Utilisateurs</h1>
					</div>
					<!-- /.col -->
					<div class="col-sm-6">
						<ol class="breadcrumb float-sm-right">
							<li class="breadcrumb-item">
								<a href="#">Dashboard</a>
							</li>
							<li class="breadcrumb-item active">Utilisateurs</li>
							<li class="breadcrumb-item active">Nouvel utilsateur</li>
						</ol>
					</div>
					<!-- /.col -->
				</div>
				<!-- /.row -->
			</div>
			<!-- /.container-fluid -->
		</div>
		<!-- /.content-header -->

		<!-- Main content -->
		<section class="content">

			<div class="container-fluid">

					<div class="row">
						<!-- left column -->
						<div class="col">
							<!-- general form elements -->
							<div class="card card-primary">
								<div class="card-header">
									<h3 class="card-title">
										Informations sur l'utilisateur
									</h3>
								</div>
								{{ form_start(userForm) }}
								<div class="row">
									<div class="col-md-6">
										<div class="card-body">
											<div class="form-group">
												<label for="Nom">Nom</label>
												{{ form_widget(userForm.nom_utilisateur) }}
											</div>

											<div class="form-group">
												<label for="Prenom">Prenom</label>
												{{ form_widget(userForm.prenom_utilisateur) }}
											</div>

											<div class="form-group">
												<label for="Email">Email</label>
												{{ form_widget(userForm.email_utilisateur) }}
											</div>

											<div class="form-group">
												<label for="exampleInputFile">Sexe</label>
												<input type="text" class="form-control"  placeholder="Sexe" disabled>
											</div>
										</div>
									</div>

									<div class="col-md-6">
										<div class="card-body">
										  <div class="form-group">
												<label for="Date">Date de naissance</label>
											    <div class="input-group date" id="dateNaissance" data-target-input="nearest">
                                                   {{ form_widget(userForm.date_naissance) }}
													<div class="input-group-append" data-target="#dateNaissance" data-toggle="datetimepicker">
														<div class="input-group-text"><i class="fa fa-calendar"></i></div>
													</div>
												</div>
											</div>

											<div class="form-group">
												<label for="Telephone">Telephone</label>
										   	{{ form_widget(userForm.phone_utilisateur) }}
											</div>

											<div class="form-group">
												<label for="Adresse">Adresse</label>
												{{ form_widget(userForm.adresse_utilisateur) }}
											</div>

											<label for="Photo">Photo</label>
											<div class="custom-file">
												{{ form_widget(userForm.photo, {'id': 'customFile'}) }}
												<label class="custom-file-label" for="customFile">Choisir un fichier</label>
											</div>
										</div>
									</div>
								</div>

								<div class="card-footer text-right">
							     	{{ form_widget(userForm.submit) }}
								</div>

								 {{ form_rest(userForm) }}

								{{ form_end(userForm) }}

							</div>
							<!-- /.card -->
						</div>

					</div>
					<!-- /.row -->

				</div>

			</section>
			<!-- /.content -->

		</div>

		{% block javascripts %}

			<script src=" {{asset('assets/js/custom_input.min.js')}} "></script>
			<script src=" {{asset('assets/js/moment.min.js')}}"></script>
			<script src=" {{asset('assets/js/tempusdominus.min.js')}}"></script>

			{% for message in app.flashes('success') %}
				<script type="text/javascript">
					$(function () {
						toastr.success("{{ message }}" );
					});
				</script>
	     	{% endfor %}

			<script type="text/javascript">
				$(function () {
					bsCustomFileInput.init();
			        $('#dateNaissance').datetimepicker({ format: 'DD/MM/yyyy'  });
				});
			</script>

		{% endblock %}

	{% endblock %}

templates/utilisateur/see_utilisateur.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Matrix - Add - Utilisateurs
{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{asset('assets/css/dataTables.bootstrap4.min.css') }}">
	<link rel="stylesheet" href="{{asset('assets/css/utilisateur.css') }}">
    <link  rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap-grid.min.css" />


{% endblock %}


{% block cental_content %}

	<!-- Content Wrapper. Contains page content -->
	<div class="content-wrapper">

		<!-- Content Header (Page header) -->
		<div class="content-header">
			<div class="container-fluid">
				<div class="row mb-2">
					<div class="col-sm-6">
						<h1 class="m-0">Profile</h1>
					</div>
					<!-- /.col -->
					<div class="col-sm-6">
						<ol class="breadcrumb float-sm-right">
							<li class="breadcrumb-item">
								<a href="#">Dashboard</a>
							</li>
							<li class="breadcrumb-item active">Utilisateurs</li>
							<li class="breadcrumb-item active">Profiler</li>
						</ol>
					</div>
					<!-- /.col -->
				</div>
				<!-- /.row -->
			</div>
			<!-- /.container-fluid -->
		</div>
		<!-- /.content-header -->

		<!-- Main content -->
		<section class="content">

			<div class="container-fluid">

				<div class="row">
					<div class="col-md-3">

						<!-- Profile Image -->
						<div class="card card-primary card-outline">
							<div class="card-body box-profile">
								<div class="text-center">
									<img class="profile-user-img img-fluid img-circle" src="{{asset('images/user4-128x128.jpg') }} " alt="User profile picture">
								</div>

								<h3 class="profile-username text-center"> {{ user.getNomUtilisateur() }} {{ user.getPrenomUtilisateur() }} </h3>

								<p class="text-muted text-center"> {{ user.getEmailUtilisateur() }} </p>

								<ul class="list-group list-group-unbordered mb-3">
									<li class="list-group-item">
										<b>Nom</b>
										<a class="float-right">{{ user.getNomUtilisateur() }}</a>
									</li>
									<li class="list-group-item">
										<b>Prenom</b>
										<a class="float-right">{{ user.getPrenomUtilisateur() }}</a>
									</li>

									<li class="list-group-item">
										<b>Email</b>
										<a class="float-right">{{ user.getEmailUtilisateur() }}</a>
									</li>

									<li class="list-group-item">
										<b>Né le
										</b>
										<a class="float-right">{{ user.DateNaissance() | date("m/d/Y") }}</a>
									</li>

									<li class="list-group-item">
										<b>Telephone
										</b>
										<a class="float-right">{{ user.getPhoneUtilisateur() }}</a>
									</li>

									<li class="list-group-item">
										Adresse
										<a class="float-right">{{ user.getAdresseUtilisateur() }}</a>
									</li>

								</ul>

								<a href=" {{ path('edit_utilisateur', {'id': user.id} )  }} " class="btn btn-primary btn-block">
									<b>
										<i class="fa fa-pencil" aria-hidden="true"></i>
										Modifier l'utilisateur</b>
								</a>
							</div>
							<!-- /.card-body -->
						</div>
						<!-- /.card -->
					</div>
					<!-- /.col -->
					<div class="col-md-9">
						<div class="card">
							<div class="card-header p-2">
								<ul class="nav nav-pills">
									<li class="nav-item">
										<a class="nav-link active" href="#activity" data-toggle="tab">Equipements Affectés</a>
									</li>
								</ul>
							</div>
							<!-- /.card-header -->
							<div class="card-body">
								<div class="tab-content grid">
									<div class="active tab-pane" id="activity">
                                    <div class="row">
                                    {% for userAffection in user.getAffections %}
                                       <div class="col-md-4 mb-2">
											<div class="card">
												<div class="card-body">
													<h5 class="card-title">Card title</h5>
													<p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
												</div>
												<div class="card-footer">
                                                <div class="footer-content d-flex justify-content-between align-self-center">
                                                	 <small class="text-muted">Affectés il y a 3j </small>
                                                   <div class="dropdown">
														<a class="btn-sm btn-secondary " type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
															<i class="fa fa-ellipsis-h" aria-hidden="true"></i>
														</a>
														<ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
															<li><a class="dropdown-item" href="#"> Retirer   </a></li>
															<li><hr class="dropdown-divider"></li>
															<li><a class="dropdown-item" href="#"> Details </a></li>
														</ul>
													</div>
                                                </div>

												</div>
											</div>
										</div>

										{% else %}

										<div class="col-12 text-center">
										Pas d'equipement affecte a cet utilisateur pour le moment
										</div>



                                    {% endfor %}

                                  </div>

									</div>

                                    {# PLACER UNE SECTION ICI #}

								</div>
								<!-- /.tab-content -->
							</div>
							<!-- /.card-body -->
						</div>
						<!-- /.card -->
					</div>
					<!-- /.col -->
				</div>


			</div>

		</section>

		<!-- /.content -->
	</div>
	<!-- /.content-wrapper -->


	{% block javascripts %}{% endblock %}


{% endblock %}

templates/utilisateur/utilisateur.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Matrix - Utilisateurs
{% endblock %}


{% block stylesheets %}
	<link rel="stylesheet" href="{{asset('assets/css/dataTables.bootstrap4.min.css') }}">
	<link rel="stylesheet" href="{{asset('assets/css/utilisateur.css') }}">
{% endblock %}


{% block cental_content %}

	<!-- Content Wrapper. Contains page content -->
	<div
		class="content-wrapper">
		<!-- Content Header (Page header) -->
		<div class="content-header">
			<div class="container-fluid">
				<div class="row mb-2">
					<div class="col-sm-6">
						<h1 class="m-0">Utilisateurs</h1>
					</div>
					<!-- /.col -->
					<div class="col-sm-6">
						<ol class="breadcrumb float-sm-right">
							<li class="breadcrumb-item">
								<a href="#">Dashboard</a>
							</li>
							<li class="breadcrumb-item active">Utilisateurs</li>
						</ol>
					</div>
					<!-- /.col -->
				</div>
				<!-- /.row -->
			</div>
			<!-- /.container-fluid -->
		</div>
		<!-- /.content-header -->

		<!-- Main content -->
		<section class="content">

			<div class="container-fluid">

				<div class="row">

					<div class="col-12">
						<div class="card">
							<div class="card-header d-flex justify-content-between">
								<input type="search" id="usersearcher" class="form-control col-6" placeholder="Trouver un utilisateur ... ">
								<div class="col-6 text-right">
									<a href=" {{ path('add_utilisateur') }} " class="btn btn-primary ">
										<i class="fa fa-plus" aria-hidden="true"></i>
										Nouvel utilisateur
									</a>
								</div>
							</div>

							<div class="card-body">
								<div class="table-responsive">
									<table id="userstable" class="table table-bordered table-hover">
										<thead>
											<tr>
												<th>Nom utilisateurs</th>
												<th>Prenom utilisateurs</th>
												<th>Telephones</th>
												<th>Emails</th>
												<th>Actions</th>
											</tr>
										</thead>
										<tbody>

											{% for user in allUsers %}
												<tr>
													<td>
														{{ user.nomUtilisateur }}
													</td>
													<td>{{ user.prenomUtilisateur }}
													</td>
													<td>{{ user.phoneUtilisateur }}
													</td>
													<td>
														{{ user.emailUtilisateur }}
													</td>
													<td>
													<div class="dropdown">
														<a class="btn-sm btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
															Action
														</a>
														<ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
															<li><a class="dropdown-item" href=" {{ path('edit_utilisateur', {'id': user.id} )  }}  ">Editer</a></li>
															<li><hr class="dropdown-divider"></li>
															<li><a  href=" {{ path('profile_utilisateur') }}  " class="dropdown-item" href="#">Voir profile</a></li>
														</ul>
													</div>

													</td>
												</tr>

											{% else %}

												<tr>
													<td colspan="5" class="text-center">
														Pas d'utilisateur pour le moment
													</td>
												</tr>

											{% endfor %}

										</tbody>
									</table>

								</div>

							</div>
							<!-- /.card-body -->
						</div>
					</div>

				</div>

			</div>

		</section>
		<!-- /.content -->

	</div>
	<!-- /.content-wrapper -->


	{% block javascripts %}
		<script src="{{ asset('assets/js/jquery.dataTables.min.js') }} "></script>
		<script src="{{ asset('assets/js/dataTables.bootstrap4.min.js') }}"></script>
		<script type="text/javascript">
			var searchField = $('#usersearcher')
			var userTable = $('#userstable').DataTable({
					"paging": true,
					"lengthChange": false,
					"searching": true,
					"ordering": true,
					"info": true,
					"autoWidth": false,
					"responsive": true,
					language: {
					url: "{{ asset('assets/tools/datatable_fr.json') }}"
			}

		});


    searchField.keyup(function () {
				console.log(userTable);
				userTable.search(searchField.val()).draw();
	})
		</script>


	{% endblock %}


{% endblock %}