src/Entity/Fournisseur.php
<?php

namespace App\Entity;

use App\Repository\FournisseurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FournisseurRepository::class)]
class Fournisseur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom_fournisseur;

    #[ORM\Column(type: 'string', length: 255)]
    private $prenom_fournisseur;

    #[ORM\Column(type: 'string', length: 255)]
    private $adresse_fournisseur;

    #[ORM\Column(type: 'string', length: 255)]
    private $email_fournisseur;

    #[ORM\Column(type: 'bigint')]
    private $phone_fournisseur;

    #[ORM\OneToMany(mappedBy: 'fournisseur_id', targetEntity: Equipement::class)]
    private $equipements;

    public function __construct()
    {
        $this->equipements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomFournisseur(): ?string
    {
        return $this->nom_fournisseur;
    }

    public function setNomFournisseur(string $nom_fournisseur): self
    {
        $this->nom_fournisseur = $nom_fournisseur;

        return $this;
    }

    public function getPrenomFournisseur(): ?string
    {
        return $this->prenom_fournisseur;
    }

    public function setPrenomFournisseur(string $prenom_fournisseur): self
    {
        $this->prenom_fournisseur = $prenom_fournisseur;

        return $this;
    }

    public function getAdresseFournisseur(): ?string
    {
        return $this->adresse_fournisseur;
    }

    public function setAdresseFournisseur(string $adresse_fournisseur): self
    {
        $this->adresse_fournisseur = $adresse_fournisseur;

        return $this;
    }

    public function getEmailFournisseur(): ?string
    {
        return $this->email_fournisseur;
    }

    public function setEmailFournisseur(string $email_fournisseur): self
    {
        $this->email_fournisseur = $email_fournisseur;

        return $this;
    }

    public function getPhoneFournisseur(): ?string
    {
        return $this->phone_fournisseur;
    }

    public function setPhoneFournisseur(string $phone_fournisseur): self
    {
        $this->phone_fournisseur = $phone_fournisseur;

        return $this;
    }

    /**
     * @return Collection<int, Equipement>
     */
    public function getEquipements(): Collection
    {
        return $this->equipements;
    }

    public function addEquipement(Equipement $equipement): self
    {
        if (!$this->equipements->contains($equipement)) {
            $this->equipements[] = $equipement;
            $equipement->setFournisseurId($this);
        }

        return $this;
    }

    public function removeEquipement(Equipement $equipement): self
    {
        if ($this->equipements->removeElement($equipement)) {
            // set the owning side to null (unless already changed)
            if ($equipement->getFournisseurId() === $this) {
                $equipement->setFournisseurId(null);
            }
        }

        return $this;
    }
}

src/Form/FournisseurType.php
<?php

namespace App\Form;

use App\Entity\Fournisseur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FournisseurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_fournisseur', TextType::class, [
                'required' => true,
                'attr' => [
                    'class' => "form-control",
                    'placeholder' => "Enter le nom du fournisseur",
                ]
            ])
            ->add('prenom_fournisseur', TextType::class, [
                'required' => true,
                'attr' => [
                    'class' => "form-control",
                    'placeholder' => "Enter le prenom du fournisseur",
                ]
            ])
            ->add('adresse_fournisseur', TextType::class, [
                'required' => true,
                'attr' => [
                    'class' => "form-control",
                    'placeholder' => "Enter l'adresse du fournisseur",
                ]
            ])
            ->add('email_fournisseur', EmailType::class, [
                'required' => true,
                'attr' => [
                    'class' => "form-control",
                    'placeholder' => "Enter l'adresse du fournisseur",
                ]
            ])
            ->add('phone_fournisseur', TelType::class, [
                'required' => true,
                'attr' => [
                    'class' => "form-control",
                    'placeholder' => "XXXXXXXX",
                ]
            ])
        
            ->add('submit', SubmitType::class, [
                'label' =>"Enregistrer",
                'attr' => [
                    'class' => "btn btn-primary",
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Fournisseur::class,
        ]);
    }
}

src/Controller/FournisseurController.php
<?php

namespace App\Controller;

use App\Entity\Fournisseur;
use App\Form\FournisseurType;
use App\Repository\FournisseurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FournisseurController extends AbstractController
{
    /**
     * @Route("/fournisseur", name="fournisseur")
     */
    public function fournisseur(FournisseurRepository $fournisseurRepo): Response
    {
          
        $allFournisseurs = $fournisseurRepo->findAll();

        return $this->render('fournisseur/fournisseur.html.twig', [
            'allFournisseurs' => $allFournisseurs,
        ]);
    }

    /**
     * @Route("/add/fournisseur", name="add_fournisseur")
     * @Route("/edit/{id}/fournisseur", name="edit_fournisseur")
     */
    public function addFournisseur(Fournisseur $fournisseur =null, Request $request, EntityManagerInterface $manager): Response
    {
        if ($fournisseur) {

            $fournisseurForm = $this->createForm(FournisseurType::class, $fournisseur);
            $fournisseurForm->handleRequest($request);
            if ($fournisseurForm->isSubmitted() && $fournisseurForm->isValid()) {
            $manager->persist($fournisseur);
            $manager->flush();
            $this->addFlash('success',  'Fournisseur modifié avec succès !! ');
            return $this->redirectToRoute('fournisseur');
            }


        }  else {
            // On veut faire une insertion
            $fournisseur = new Fournisseur();
            $fournisseurForm = $this->createForm(FournisseurType::class, $fournisseur);
            $fournisseurForm->handleRequest($request);

            if ($fournisseurForm->isSubmitted() && $fournisseurForm->isValid()) {
            $manager->persist($fournisseur);
            $manager->flush();
            $this->addFlash('success',  'Fournisseur creer avec succès !! ');
            return $this->redirectToRoute('fournisseur');
            }

        }
        return $this->render('fournisseur/add_fournisseur.html.twig', [
            'fournisseurForm' => $fournisseurForm->createView(),

        ]);
    }
}

templates/fournisseur/add_fournisseur.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Matrix - Add - Fournisseurs
{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{asset('assets/css/dataTables.bootstrap4.min.css') }}">
	<link rel="stylesheet" href="{{asset('assets/css/fournisseur.css') }}">
	<link rel="stylesheet" href="{{ asset('assets/css/tempusdominus.min.css') }} ">
{% endblock %}


{% block cental_content %}

	<!-- Content Wrapper. Contains page content -->
	<div
		class="content-wrapper">
		<!-- Content Header (Page header) -->
		<div class="content-header">
			<div class="container-fluid">
				<div class="row mb-2">
					<div class="col-sm-6">
						<h1 class="m-0">Fournisseur</h1>
					</div>
					<!-- /.col -->
					<div class="col-sm-6">
						<ol class="breadcrumb float-sm-right">
							<li class="breadcrumb-item">
								<a href="#">Dashboard</a>
							</li>
							<li class="breadcrumb-item active">Fournisseur</li>
							<li class="breadcrumb-item active">Nouveau Fournisseur</li>
						</ol>
					</div>
					<!-- /.col -->
				</div>
				<!-- /.row -->
			</div>
			<!-- /.container-fluid -->
		</div>
		<!-- /.content-header -->

		<!-- Main content -->
		<section class="content">

			<div class="container-fluid">

				<div class="container-fluid">
					<div
						class="row">
						<!-- left column -->
						<div
							class="col">
							<!-- general form elements -->
							<div class="card card-primary">
								<div class="card-header">
									<h3 class="card-title">
										Informations le fournisseur
									</h3>
								</div>
								{{ form_start(fournisseurForm) }}
								<div class="row">
									<div class="col-md-6">
										<div class="card-body">
											<div class="form-group">
												<label for="Nom">Nom</label>
												{{ form_widget(fournisseurForm.nom_fournisseur) }}
											</div>

											<div class="form-group">
												<label for="Prenom">Prenom</label>
												{{ form_widget(fournisseurForm.prenom_fournisseur) }}
											</div>

											<div class="form-group">
												<label for="Email">Email</label>
												{{ form_widget(fournisseurForm.email_fournisseur) }}
											</div>

											<div class="form-group">
												<label for="exampleInputFile">Sexe</label>
												<input type="text" class="form-control"  placeholder="Sexe" disabled>
											</div>
										</div>
									</div>

									<div class="col-md-6">
										<div class="card-body">
										  <div class="form-group">
												<label for="Date">Etablissement</label>
											   <input type="text" class="form-control"  placeholder="Etablissement Coming soon......." disabled>
											</div>

											<div class="form-group">
												<label for="Telephone">Telephone</label>
										   	{{ form_widget(fournisseurForm.phone_fournisseur) }}
											</div>

											<div class="form-group">
												<label for="Adresse">Adresse</label>
												{{ form_widget(fournisseurForm.adresse_fournisseur) }}
											</div>

											<label for="Photo">Photo</label>
											<div class="custom-file">
											 <input type="file" class="form-control"  placeholder="Photo Coming soon......." disabled>
												<label class="custom-file-label" for="customFile">Choisir un fichier</label>
											</div>
										</div>
									</div>
								</div>

								<div class="card-footer text-right">
							     	{{ form_widget(fournisseurForm.submit) }}
								</div>

								 {{ form_rest(fournisseurForm) }}

								{{ form_end(fournisseurForm) }}

							</div>
							<!-- /.card -->
						</div>

					</div>
					<!-- /.row -->

				</div>

			</section>
			<!-- /.content -->

		</div>

		{% block javascripts %}

			<script src=" {{asset('assets/js/custom_input.min.js')}} "></script>
			<script src=" {{asset('assets/js/moment.min.js')}}"></script>
			<script src=" {{asset('assets/js/tempusdominus.min.js')}}"></script>

			{% for message in app.flashes('success') %}
				<script type="text/javascript">
					$(function () {
						toastr.success("{{ message }}" );
					});
				</script>
	     	{% endfor %}

			<script type="text/javascript">
				$(function () {
					bsCustomFileInput.init();
			        $('#dateNaissance').datetimepicker({ format: 'DD/MM/yyyy'  });
				});
			</script>

		{% endblock %}

	{% endblock %}

templates/fournisseur/fournisseur.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Matrix - Fournisseur
{% endblock %}


{% block stylesheets %}
	<link rel="stylesheet" href="{{asset('assets/css/dataTables.bootstrap4.min.css') }}">
	<link rel="stylesheet" href="{{asset('assets/css/utilisateur.css') }}">
{% endblock %}


{% block cental_content %}

	<!-- Content Wrapper. Contains page content -->
	<div
		class="content-wrapper">
		<!-- Content Header (Page header) -->
		<div class="content-header">
			<div class="container-fluid">
				<div class="row mb-2">
					<div class="col-sm-6">
						<h1 class="m-0">Fournisseur</h1>
					</div>
					<!-- /.col -->
					<div class="col-sm-6">
						<ol class="breadcrumb float-sm-right">
							<li class="breadcrumb-item">
								<a href="#">Dashboard</a>
							</li>
							<li class="breadcrumb-item active">Fournisseur</li>
						</ol>
					</div>
					<!-- /.col -->
				</div>
				<!-- /.row -->
			</div>
			<!-- /.container-fluid -->
		</div>
		<!-- /.content-header -->

		<!-- Main content -->
		<section class="content">

			<div class="container-fluid">

				<div class="row">

					<div class="col-12">
						<div class="card">
							<div class="card-header d-flex justify-content-between">
								<input type="search" id="fournisseursearcher" class="form-control col-6" placeholder="Trouver un fournisseur ... ">
								<div class="col-6 text-right">
									<a href=" {{ path('add_fournisseur') }} " class="btn btn-primary ">
										<i class="fa fa-plus" aria-hidden="true"></i>
										Nouveau Fournisseur
									</a>
								</div>
							</div>

							<div class="card-body">
								<div class="table-responsive">
									<table id="fournisseurtable" class="table table-bordered table-hover">
										<thead>
											<tr>
												<th>Nom fournisseur</th>
												<th>Prenom fournisseur</th>
												<th>Telephones</th>
												<th>Emails</th>
												<th>Actions</th>
											</tr>
										</thead>
										<tbody>

											{% for fournisseur in allFournisseurs %}
												<tr>
													<td>
														{{ fournisseur.nomFournisseur }}
													</td>
													<td>{{ fournisseur.prenomFournisseur }}
													</td>
													<td>{{ fournisseur.phoneFournisseur }}
													</td>
													<td>
														{{ fournisseur.emailFournisseur }}
													</td>
													<td>
													<div class="dropdown">
														<a class="btn-sm btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
															Action
														</a>
														<ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
															<li><a class="dropdown-item" href=" {{path('edit_fournisseur', {'id': fournisseur.id})}} ">Editer</a></li>
															<li><hr class="dropdown-divider"></li>
															<li><a  href=" #  " class="dropdown-item" href="#">Voir profile</a></li>
														</ul>
													</div>

													</td>
												</tr>

											{% else %}

												<tr>
													<td colspan="5" class="text-center">
														Pas de fournisseur pour le moment
													</td>
												</tr>

											{% endfor %}

										</tbody>
									</table>

								</div>

							</div>
							<!-- /.card-body -->
						</div>
					</div>

				</div>

			</div>

		</section>
		<!-- /.content -->

	</div>
	<!-- /.content-wrapper -->


	{% block javascripts %}
		<script src="{{ asset('assets/js/jquery.dataTables.min.js') }} "></script>
		<script src="{{ asset('assets/js/dataTables.bootstrap4.min.js') }}"></script>

		{% for message in app.flashes('success') %}
			<script type="text/javascript">
				$(function () {
					toastr.success("{{ message }}");
				});
			</script>
		{% endfor %}

		<script type="text/javascript">
				var searchField = $('#fournisseursearcher')
				var fournisseurTable = $('#fournisseurtable').DataTable({
						"paging": true,
						"lengthChange": false,
						"searching": true,
						"ordering": true,
						"info": true,
						"autoWidth": false,
						"responsive": true,
						language: {
						url: "{{ asset('assets/tools/datatable_fr.json') }}"
				}
			});

			searchField.keyup(function () {
						console.log(fournisseurTable);
						fournisseurTable.search(searchField.val()).draw();
			})

		</script>



	{% endblock %}


{% endblock %}